FROM openjdk:17-oracle

WORKDIR /home/app

COPY /auth-service/target/auth-service-0.0.1-SNAPSHOT.jar /app/auth-service-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java", "-jar","auth-service-0.0.1-SNAPSHOT.jar"]
