name: build code

on:
    push:
        branches:
            - main
        paths:
            - 'auth-service/**'
            - 'config-server/**'

jobs:
  build:  
    runs-on: ubuntu-latest
    strategy:
        matrix:
            microservice:
                - auth-service
                - config-server
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Build with Maven
        working-directory: ${{ matrix.microservice }}
        run: mvn  clean package -DskipTests

      - name: upload jar file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.microservice }}

      - name: Configure JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
                version: latest
        env: 
          JF_URL: https://trial1dnxmv.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.JFROG }}
          
    
      - name: Upload artifact to JFrog
        run: |
          jfrog rt u target/*.jar javamicroservice/${{ matrix.microservice }}/
        