name: build code

on:
    push:
        branches:
            - main
        paths:
            - 'auth-service/**'
            - 'config-server/**'

jobs:
  build:  
    runs-on: ubuntu-latest
    strategy:
        matrix:
            microservice:
                - auth-service
                - config-server
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Build with Maven
        working-directory: ${{ matrix.microservice }}
        run: mvn  clean package -DskipTests

      - name: upload jar file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.microservice }}
          path: ${{ matrix.microservice }}/target/*.jar

      - name: Configure JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
                version: latest
        env: 
          JF_URL: https://trialmx0g3h.jfrog.io/
          JF_ACCESS_TOKEN: "${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}"
          JF_REPO: javamicroservice
     
        # checking the path to microservice
      - name: files
        run: |
            ls
          
        # checking the path to microservice
      - name: Upload artifact to JFrog
        run: |
          ls  ${{ matrix.microservice }}/target
          jfrog rt u "${{ matrix.microservice }}/target/*.jar" "javamicroservice/" --url="https://trialmx0g3h.jfrog.io/artifactory/" --access-token="${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}"
        