name: Docker Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            microservice:
                - auth-service
                - config-server
    steps:
      - name: Checkout
        uses:  actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-buildx-action@v3

     
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    
      - name: Push to Docker Hub
        run: | 
           cd ${{ matrix.microservice }}
           docker build --tag ${{ secrets.DOCKER_USERNAME }}/${{ matrix.microservice }}:latest -f Dockerfile .
          
           docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.microservice }}:latest
