name: Docker Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            microservice:
                - auth-service
                - config-server
    steps:
      - name: Checkout
        uses:  actions/checkout@v4

      - name: Set up docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          cd ${{ matrix.microservice }}
          docker build -t ${{ matrix.microservice }} .
          docker tag ${{ matrix.microservice }}:latest sakurasher/${{ matrix.microservice }}:latest

      - name: Push Docker Image
        env:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}  
        run: | 
           docker push sakurasher/${{ matrix.microservice }}:latest